import Head from 'next/head'

const styles = {
  container: {
    maxWidth: '80%',
    margin: '0 auto',
    textAlign: 'center',
    position: 'relative',
    top: '35%',
    lineHeight: '1.8rem'
  },
  superscript: {
    fontSize: '12px'
  },
  maxHeight: {
    height: '100%'
  },
}

export default function Home() {
  return (
    <div style={styles.maxHeight} >
      <Head>
        <title>Home App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{...styles.container}}>
        <h1 style={{marginBottom: '5px'}}>Hello; Welcome to my webpage!</h1>
        <p>Currently there is not much on this page, so here is an animation!</p>
        <p>Docker status: yes, i think</p>
        {/* <p>Also here is some info on how to deploy a page/app just like this to your own server.</p> */}
        <p style={{fontSize: '11px', marginTop: '5px'}}>* Queue a cube or something that will follow the cursor or something... *</p>
      </div>
    </div>
  )
}
