name: Deployment Workflow
on: workflow_dispatch
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote deploy of server via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_ADDRESS }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd dev/home
            git pull origin master
            docker stop home-tester
            docker rm home-tester
            docker rmi home-test:unstable
            docker build --no-cache -t home-test:unstable .
            docker run --name home-tester --publish 3000:3000 -d home-test:unstable
