name: Deployment Workflow
on: workflow_dispatch
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote deploy of server via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_ADDRESS }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd dev/home-test/home
            git pull origin master
            docker build -t home-test:unstable .
            docker ps -a
          
