name: Deployment Workflow
on: workflow_dispatch
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote deploy of server via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_ADDRESS }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd dev/home
            git pull origin master
          # docker build -t home-testing .
            docker ps 
          # build new image
          # delete old image/container - one idea -> append shortened commit tag to image & container as tag. 
          # run the new image via new container
          # Port is subject to change... will need to adjust workflow to get latest public IPv4 address that ISP assigns.
