name: Deployment Workflow
on: workflow_dispatch
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote deploy of server via ssh
        uses: appleboy/ssh-action@master
        with:
          # Port is subject to change... will need to adjust workflow to get latest public IPv4 address that ISP assigns.
          host: ${{ secrets.SSH_ADDRESS }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami